// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ErrorLog from "./islands/ErrorLog.tsx";
import * as $NewApp from "./islands/NewApp.tsx";
import * as $NewLog from "./islands/NewLog.tsx";
import * as $NewProgress from "./islands/NewProgress.tsx";
import * as $SeriesLog from "./islands/SeriesLog.tsx";
import * as $Victory from "./islands/Victory.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ErrorLog.tsx": $ErrorLog,
    "./islands/NewApp.tsx": $NewApp,
    "./islands/NewLog.tsx": $NewLog,
    "./islands/NewProgress.tsx": $NewProgress,
    "./islands/SeriesLog.tsx": $SeriesLog,
    "./islands/Victory.tsx": $Victory,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
